# Site settings
title: Bjorling.me
email: m@bjorling.me
description: >
    A research blog on Software-defined Solid State Drives
baseurl: "bjorling.me"
url: "http://bjorling.me" # the base hostname & protocol for your site
github_username: MatiasBjorling

# Build settings
markdown: kramdown
